LANGUAGES = {
    'English': {
        'title': "Hash Table Backward Shift Visualization Tool",
        'size_input': "Enter the size of the hash table",
        'initialize_button': "Initialize or Reset Hash Table",
        'elements_input': "Current hash table elements (comma-separated, use 'None' for empty slots):",
        'remove_input': "Enter the value of the element to remove",
        'start_removal': "Start Removal",
        'element_not_found': "Element not found in the hash table.",
        'visualization_title': "Hash Table Visualization",
        'previous_step': "Previous Step",
        'next_step': "Next Step",
        'reset_to_start': "Reset to Start",
        'jump_to_end': "Jump to End",
        'auto_play': "Auto Play",
        'pause': "Pause",
        'delay_slider': "Set delay between steps (seconds)",
        'apply_changes': "Apply Changes",
        'changes_applied': "Changes applied. The hash table has been updated.",
        'removing': "Removing {} at index {}",
        'empty_slot': "```ht[{}] = None``` - Empty the slot at index {}",
        'checking_move': "Checking if element at index {} needs to move",
        'while_loop': "```while ht[{}] is not None and {} != {}:``` - Check next slot j={}",
        'no_move_needed': "Element at index {} does not need to move",
        'moving_element': "Moving element from index {} to index {}",
        'moved_element': "Moved element {} from index {} to index {}"
    },
    'Portuguese (BR)': {
        'title': "Visualização de Supressão de Lacunas",
        'size_input': "Insira o tamanho da tabela hash",
        'initialize_button': "Inicializar ou Resetar Tabela Hash",
        'elements_input': "Elementos atuais da tabela hash (separados por vírgula, use 'None' para espaços vazios):",
        'remove_input': "Digite o valor do elemento a remover",
        'start_removal': "Iniciar Remoção",
        'element_not_found': "Elemento não encontrado na tabela hash.",
        'visualization_title': "Visualização da Tabela Hash",
        'previous_step': "Passo Anterior",
        'next_step': "Próximo Passo",
        'reset_to_start': "Reiniciar",
        'jump_to_end': "Ir para o Final",
        'auto_play': "Auto Play",
        'pause': "Pausa",
        'delay_slider': "Defina o intervalo entre passos (em segundos)",
        'apply_changes': "Aplicar Mudanças",
        'changes_applied': "Mudanças aplicadas. A tabela hash foi atualizada.",
        'removing': "Removendo {} no índice {}",
        'empty_slot': "```ht[{}] = None``` - Esvaziar o espaço no índice {}",
        'checking_move': "Verificando se o elemento no índice {} precisa ser movido",
        'while_loop': "```while ht[{}] is not None and {} != {}:``` - Verificar próximo espaço j={}",
        'no_move_needed': "Elemento no índice {} não precisa ser movido",
        'moving_element': "Movendo elemento do índice {} para o índice {}",
        'moved_element': "Elemento movido {} do índice {} para o índice {}"
    },
}
